apiVersion: batch/v1

kind: Job

metadata:
  name: study-security-job

spec:
  backoffLimit: 2

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: study-security-job
          image: study-security-job:v1
          imagePullPolicy: Never